<a href="https://colab.research.google.com/github/johanhoffman/DD2363_VT22/blob/PeterTKovacs_lab1/Lab1/PeterTKovacs-lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Lab 1: Introduction**
**Péter Kovács**

# **Abstract**

Implemented problems 1-5 from the homework assignment which are all basic linear algebra routines.

#**About the code**

A short statement on who is the author of the file, and if the code is distributed under a certain license. 

In [1]:
"""This program is a template for lab reports in the course"""
"""DD2363 Methods in Scientific Computing, """
"""KTH Royal Institute of Technology, Stockholm, Sweden."""

# Copyright (C) 2022 Péter Kovács (ptkovacs@kth.se)

# This file is part of the course DD2363 Methods in Scientific Computing
# KTH Royal Institute of Technology, Stockholm, Sweden
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This template is maintained by Johan Hoffman
# Please report problems to jhoffman@kth.se

'KTH Royal Institute of Technology, Stockholm, Sweden.'

# **Set up environment**

In [2]:
# Load neccessary modules.
from google.colab import files
import numpy as np


# **Introduction**

In this submission, I solve some introductory problems in linear algebra. Since it is just implementing well-known concepts, I will keep explanatory text to the minimal necessary amount.

In most cases, I will rely on the numpy package for python, which is just designed to work with tensors of any dimension (vectors, matrices, etc.)




# **Method**

My solution will be organized according to the problem statements. I felt that the testing should be placed right after the code for different problems so I organized my submission accordingly.

Since we are required to include testing protocols in our functions, I implement them first. I check for having float inputs and matching dimensions.

### 0) preliminary testing routines

In [3]:
def is_float_64_array(array):
  if not type(array)==np.ndarray:
    return False
  if array.dtype==np.float64:
    return True
  else:
    return False

In [4]:
def matching_dimensions(a,b):

  '''
  Check if the input objects are ndarrays and if their dimensions match in a sense that a*b would be a valid operation
  '''

  if type(a)==np.ndarray and type(b)==np.ndarray:
    if a.shape[-1]==b.shape[0]:
      return True
  else:
    return False

In [5]:
def test_input_of_two(a,b):
  '''
  test dtype for np.float64 and matching dimensions
  '''
  if is_float_64_array(a) and is_float_64_array(b) and matching_dimensions(a,b):
    return True
  else:
    return False

With these preparations, we are ready to implement our functions

### 1) scalar product

In [6]:
def scalar_product(a,b):

  '''
  scalar product of a and b, which are supposed to be given with their coordinates in an orthonormal base
  also, they shall be np.float64 vectors
  '''

  if not test_input_of_two(a,b):
    print('dtype not float64 or non-matching dimensions')
    return None
  if len(a.shape)>1:
    print('not a vector')
    return None
  
  result=0
  for i in range(a.shape[0]):
    result+=a[i]*b[i]
  return result

In [7]:
# let us test no.1 
a=np.array([1,2,3],dtype=np.float64)
b=np.array([1,-2,0],dtype=np.float64)

print(scalar_product(a,b))

-3.0


In [8]:
# let us test no.2 
a=np.random.standard_normal(3)
b=np.random.standard_normal(3)

print(scalar_product(a,b))
print(a.dot(b))

-0.17209025330317126
-0.1720902533031712


So it seems we are good this time (one 'obvious for human' and one 'check with builtin' test)

### 2) matrix-vector product

In [9]:
def matrix_vector_product(A,b):

  '''
  matrix-vector product of A and b, coordinates are supposed to be given in an orthonormal basis
  also, they shall be np.float64 arrays
  '''

  if not test_input_of_two(A,b):
    print('dtype not float64 or non-matching dimensions')
    return None
  if len(A.shape)!=2 or len(b.shape)!=1:
    print('not a matrix-vector pair')
    return None
  
  r=np.zeros(A.shape[0],np.float64)
  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      r[i]+=A[i,j]*b[j]
  return r

In [10]:
# let us test no.1 
A=np.array([[1,2,3],[1,2,3]],dtype=np.float64)
b=np.array([1,-2,0],dtype=np.float64)

print(matrix_vector_product(A,b))

[-3. -3.]


In [11]:
# let us test no.2 
A=np.random.standard_normal((3,2))
b=np.random.standard_normal(2)

print(matrix_vector_product(A,b))
print(A.dot(b))

[-0.32880825 -0.59595946  0.2032501 ]
[-0.32880825 -0.59595946  0.2032501 ]


We are just fine again

### 3) matrix-matrix product


In [12]:
def matrix_matrix_product(A,B):

  '''
  matrix-matrix product of A and B, coordinates are supposed to be given in an orthonormal basis
  also, they shall be np.float64 arrays
  '''

  if not test_input_of_two(A,B):
    print('dtype not float64 or non-matching dimensions')
    return None
  if len(A.shape)!=2 or len(B.shape)!=2:
    print('not a matrix-matrix pair')
    return None
  
  r=np.zeros((A.shape[0],B.shape[-1]),np.float64)
  for i in range(A.shape[0]):
    for j in range(B.shape[-1]):
      for k in range(A.shape[-1]):
        r[i,j]+=A[i,k]*B[k,j]
  return r

In [13]:
# let us test no.1 
A=np.array([[1,2,3],[1,2,3]],dtype=np.float64)

print(matrix_matrix_product(A,A.T))

[[14. 14.]
 [14. 14.]]


In [14]:
# let us test no.2 
A=np.random.standard_normal((3,2))
B=np.random.standard_normal((2,3))

print(matrix_matrix_product(A,B))
print(A.dot(B))

[[ 1.54803394  0.07910916 -1.91554791]
 [-0.37702779 -0.32822855  0.5014984 ]
 [-0.51550487  0.53793778  0.57403602]]
[[ 1.54803394  0.07910916 -1.91554791]
 [-0.37702779 -0.32822855  0.5014984 ]
 [-0.51550487  0.53793778  0.57403602]]


We are fine again

### 4) Euclidean norm

In [15]:
def euclidean_norm(x):

  '''
  calculate eulidean (L2) norm of np.float64 array x
  '''

  if not is_float_64_array(x) or len(x.shape)>1:
    print('not float vector')
    return None
  else:
    return np.sqrt(scalar_product(x,x))


In [16]:
# let us test no.1 
x=np.array([1,2,3],dtype=np.float64)

print(euclidean_norm(x))

3.7416573867739413


In [17]:
# let us test no.1 
x=np.random.standard_normal(5)

print(euclidean_norm(x))
print(np.linalg.norm(x))

1.7064425534967473
1.7064425534967473


OK again

### 5) Euclidean distance

In [18]:
def euclidean_distance(a,b):

  '''
  calculate eucliean distance of two np.float64 vectors
  '''


  if not test_input_of_two(a,b):
    print('dtype not float64 or non-matching dimensions')
    return None
  if len(a.shape)>1:
    print('not a vector')
    return None

  return euclidean_norm(a-b)


In [19]:
# let us test no.1 
a=np.array([1,2,3],dtype=np.float64)
b=np.array([1,-2,0],dtype=np.float64)

print(euclidean_distance(a,b))

5.0


In [20]:
# let us test no.2 
a=np.random.standard_normal(3)
b=np.random.standard_normal(3)

print(euclidean_distance(a,b))
print(np.linalg.norm(a-b))

1.9899427123544275
1.9899427123544273


so OK again

# **Summary, discussion**

To sum up, our methods just work as expected, which is kind of non-surprising for such basic tasks.